/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _harness_remote_dsh_wechat_remote_agentInputs_capabilities_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentInputs_capabilities_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentInputs_capabilities_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
}))
let _harness_remote_dsh_wechat_remote_agentInputs_capabilities_result$schema$value
const _harness_remote_dsh_wechat_remote_agentInputs_capabilities_result$schema = () => (_harness_remote_dsh_wechat_remote_agentInputs_capabilities_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentInputs_upload_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentInputs_upload_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentInputs_upload_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'name': z.string(),
  'data': z.union([z.undefined(), z.string()]).optional(),
  'descriptorJson': z.union([z.undefined(), z.string()]).optional(),
}))
let _harness_remote_dsh_wechat_remote_agentInputs_upload_result$schema$value
const _harness_remote_dsh_wechat_remote_agentInputs_upload_result$schema = () => (_harness_remote_dsh_wechat_remote_agentInputs_upload_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_capabilities_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_capabilities_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_capabilities_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'purpose': z.union([z.undefined(), z.literal("sessionArchive")]).optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_capabilities_result$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_capabilities_result$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_capabilities_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_chunk_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_chunk_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_chunk_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'transferId': z.string(),
  'offset': z.number(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_chunk_result$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_chunk_result$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_chunk_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_list_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_list_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_list_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'directoryId': z.union([z.undefined(), z.string()]).optional(),
  'cursor': z.union([z.undefined(), z.number()]).optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_list_result$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_list_result$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_list_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_prepare_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_prepare_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_prepare_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'id': z.string(),
  'delivery': z.union([z.literal("object"), z.literal("chunks")]),
}))
let _harness_remote_dsh_wechat_remote_agentResources_prepare_result$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_prepare_result$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_prepare_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_prepareArchive_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_prepareArchive_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_prepareArchive_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'delivery': z.union([z.literal("object"), z.literal("chunks")]),
}))
let _harness_remote_dsh_wechat_remote_agentResources_prepareArchive_result$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_prepareArchive_result$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_prepareArchive_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_release_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_release_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_release_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'transferId': z.string(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_release_result$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_release_result$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_release_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_resolve_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_resolve_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_resolve_parameter_0$schema$value ??= z.object({
  'scope': z.string(),
  'reference': z.string(),
}))
let _harness_remote_dsh_wechat_remote_agentResources_resolve_result$schema$value
const _harness_remote_dsh_wechat_remote_agentResources_resolve_result$schema = () => (_harness_remote_dsh_wechat_remote_agentResources_resolve_result$schema$value ??= z.object({
  'ok': z.boolean().readonly(),
  'valueJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_parameter_0$schema$value ??= z.object({
  'sessionId': z.string().readonly(),
  'attachments': z.array(z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.union([z.undefined(), z.string()]).readonly().optional(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
}))
let _harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'descriptors': z.array(z.object({
  'attachmentId': z.string().readonly(),
  'descriptor': z.object({
  'v': z.literal(1).readonly(),
  'scheme': z.literal("xsalsa20-poly1305-chunks-v1").readonly(),
  'objectId': z.string().readonly(),
  'key': z.string().readonly(),
  'noncePrefix': z.string().readonly(),
  'plainBytes': z.number().readonly(),
  'cipherBytes': z.number().readonly(),
  'chunkBytes': z.number().readonly(),
  'contentKind': z.literal("image").readonly(),
  'mediaType': z.string().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
  'expiresAt': z.number().readonly(),
}).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("invalid-attachment-request"), z.literal("attachment-unavailable"), z.literal("attachment-object-unavailable")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})]))
let _harness_remote_dsh_wechat_remote_wechatDirectory_create_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatDirectory_create_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatDirectory_create_parameter_0$schema$value ??= z.object({
  'path': z.string().readonly(),
  'name': z.string().readonly(),
}))
let _harness_remote_dsh_wechat_remote_wechatDirectory_create_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatDirectory_create_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatDirectory_create_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'path': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("directory-exists"), z.literal("directory-create-failed")]).readonly(),
  'path': z.string().readonly(),
  'message': z.string().readonly(),
}).readonly(),
})]))
let _harness_remote_dsh_wechat_remote_wechatDirectory_list_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatDirectory_list_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatDirectory_list_parameter_0$schema$value ??= z.object({
  'path': z.union([z.undefined(), z.string()]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_wechatDirectory_list_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatDirectory_list_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatDirectory_list_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'path': z.string().readonly(),
  'home': z.string().readonly(),
  'crumbs': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'truncated': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("directory-unreadable"), z.literal("directory-timeout"), z.literal("network-unavailable")]).readonly(),
  'path': z.string().readonly(),
  'message': z.string().readonly(),
}).readonly(),
})]))
let _harness_remote_dsh_wechat_remote_wechatDirectory_roots_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatDirectory_roots_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatDirectory_roots_parameter_0$schema$value ??= z.object({}))
let _harness_remote_dsh_wechat_remote_wechatDirectory_roots_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatDirectory_roots_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatDirectory_roots_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'home': z.string().readonly(),
  'roots': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'kind': z.union([z.literal("local"), z.literal("network"), z.literal("filesystem"), z.literal("home"), z.literal("volume")]).readonly(),
  'displayRoot': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'platform': z.union([z.literal("windows"), z.literal("macos"), z.literal("linux"), z.literal("unknown")]).readonly(),
  'rootStyle': z.union([z.literal("filesystem"), z.literal("drives")]).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.literal("drive-enumeration-failed").readonly(),
  'message': z.string().readonly(),
}).readonly(),
})]))
let _harness_remote_dsh_wechat_remote_wechatHistory_detail_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatHistory_detail_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatHistory_detail_parameter_0$schema$value ??= z.object({
  'sessionId': z.string().readonly(),
  'reference': z.string().readonly(),
  'part': z.union([z.undefined(), z.number()]).readonly().optional(),
  'offset': z.union([z.undefined(), z.number()]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_wechatHistory_detail_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatHistory_detail_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatHistory_detail_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'payloadJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'snapshotJson': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("invalid-history-request"), z.literal("history-unavailable"), z.literal("history-pagination-invalid"), z.literal("history-busy"), z.literal("history-detail-unavailable"), z.literal("invocation-unavailable")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})]))
let _harness_remote_dsh_wechat_remote_wechatHistory_page_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatHistory_page_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatHistory_page_parameter_0$schema$value ??= z.object({
  'sessionId': z.string().readonly(),
  'beforeSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'maxMessages': z.union([z.undefined(), z.number()]).readonly().optional(),
  'delivery': z.union([z.undefined(), z.literal("auto"), z.literal("inline")]).readonly().optional(),
  'acceptInlineArchive': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_wechatHistory_page_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatHistory_page_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatHistory_page_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'payloadJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'snapshotJson': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("invalid-history-request"), z.literal("history-unavailable"), z.literal("history-pagination-invalid"), z.literal("history-busy"), z.literal("history-detail-unavailable"), z.literal("invocation-unavailable")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})]))
let _harness_remote_dsh_wechat_remote_wechatHistory_window_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatHistory_window_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatHistory_window_parameter_0$schema$value ??= z.object({
  'sessionId': z.string().readonly(),
  'beforeSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'maxMessages': z.union([z.undefined(), z.number()]).readonly().optional(),
  'delivery': z.union([z.undefined(), z.literal("auto"), z.literal("inline")]).readonly().optional(),
  'acceptInlineArchive': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}))
let _harness_remote_dsh_wechat_remote_wechatHistory_window_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatHistory_window_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatHistory_window_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'payloadJson': z.union([z.undefined(), z.string()]).readonly().optional(),
  'snapshotJson': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("invalid-history-request"), z.literal("history-unavailable"), z.literal("history-pagination-invalid"), z.literal("history-busy"), z.literal("history-detail-unavailable"), z.literal("invocation-unavailable")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})]))
let _harness_remote_dsh_wechat_remote_wechatHost_describe_parameter_0$schema$value
const _harness_remote_dsh_wechat_remote_wechatHost_describe_parameter_0$schema = () => (_harness_remote_dsh_wechat_remote_wechatHost_describe_parameter_0$schema$value ??= z.object({}))
let _harness_remote_dsh_wechat_remote_wechatHost_describe_result$schema$value
const _harness_remote_dsh_wechat_remote_wechatHost_describe_result$schema = () => (_harness_remote_dsh_wechat_remote_wechatHost_describe_result$schema$value ??= z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'computerName': z.string().readonly(),
  'pluginVersion': z.string().readonly(),
  'hostArch': z.string().readonly(),
  'updateProtocolVersion': z.literal(1).readonly(),
  'descriptorVersion': z.literal(1).readonly(),
  'hostId': z.string().readonly(),
  'agentInstanceId': z.string().readonly(),
  'agentKind': z.literal("deepseek-harness").readonly(),
  'agentName': z.literal("DeepSeek Harness").readonly(),
  'agentVersion': z.string().readonly(),
  'hostPlatform': z.object({
  'kind': z.union([z.literal("windows"), z.literal("macos"), z.literal("linux"), z.literal("unknown")]).readonly(),
  'name': z.string().readonly(),
  'pathStyle': z.union([z.literal("windows"), z.literal("posix")]).readonly(),
  'directoryRootStyle': z.union([z.literal("filesystem"), z.literal("drives")]).readonly(),
}).readonly(),
  'capabilities': z.array(z.object({
  'id': z.string().readonly(),
  'version': z.number().readonly(),
})).readonly(),
  'gate': z.union([z.undefined(), z.object({
  'profileScope': z.string().readonly(),
  'source': z.union([z.literal("legacy-default"), z.literal("profile-derived"), z.literal("environment-override")]).readonly(),
  'publicDoor': z.object({
  'bind': z.string().readonly(),
  'port': z.number().readonly(),
  'state': z.union([z.literal("starting"), z.literal("listening"), z.literal("unavailable"), z.literal("stopped")]).readonly(),
  'errorCode': z.union([z.literal(null), z.string()]).readonly(),
  'message': z.union([z.literal(null), z.string()]).readonly(),
}).readonly(),
  'localDoor': z.object({
  'bind': z.string().readonly(),
  'port': z.number().readonly(),
  'state': z.union([z.literal("starting"), z.literal("listening"), z.literal("unavailable"), z.literal("stopped")]).readonly(),
  'errorCode': z.union([z.literal(null), z.string()]).readonly(),
  'message': z.union([z.literal(null), z.string()]).readonly(),
}).readonly(),
})]).readonly().optional(),
}).readonly(),
}))

export const TYPERT = {
  package: '@harness-remote/dsh-wechat-remote',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@harness-remote/dsh-wechat-remote#agentInputs/capabilities',
      service: 'agentInputs',
      namespace: 'agentInputs',
      method: 'capabilities',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentInputs/capabilities:request',
            create: _harness_remote_dsh_wechat_remote_agentInputs_capabilities_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentInputs_capabilities_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-inputs.ts","line":30,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentInputs/upload',
      service: 'agentInputs',
      namespace: 'agentInputs',
      method: 'upload',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentInputs/upload:request',
            create: _harness_remote_dsh_wechat_remote_agentInputs_upload_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentInputs_upload_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-inputs.ts","line":35,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentResources/capabilities',
      service: 'agentResources',
      namespace: 'agentResources',
      method: 'capabilities',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentResources/capabilities:request',
            create: _harness_remote_dsh_wechat_remote_agentResources_capabilities_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentResources_capabilities_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-resources.ts","line":78,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentResources/chunk',
      service: 'agentResources',
      namespace: 'agentResources',
      method: 'chunk',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentResources/chunk:request',
            create: _harness_remote_dsh_wechat_remote_agentResources_chunk_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentResources_chunk_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-resources.ts","line":196,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentResources/list',
      service: 'agentResources',
      namespace: 'agentResources',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentResources/list:request',
            create: _harness_remote_dsh_wechat_remote_agentResources_list_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentResources_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-resources.ts","line":90,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentResources/prepare',
      service: 'agentResources',
      namespace: 'agentResources',
      method: 'prepare',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentResources/prepare:request',
            create: _harness_remote_dsh_wechat_remote_agentResources_prepare_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentResources_prepare_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-resources.ts","line":167,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentResources/prepareArchive',
      service: 'agentResources',
      namespace: 'agentResources',
      method: 'prepareArchive',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentResources/prepareArchive:request',
            create: _harness_remote_dsh_wechat_remote_agentResources_prepareArchive_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentResources_prepareArchive_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-resources.ts","line":156,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentResources/release',
      service: 'agentResources',
      namespace: 'agentResources',
      method: 'release',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentResources/release:request',
            create: _harness_remote_dsh_wechat_remote_agentResources_release_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentResources_release_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-resources.ts","line":208,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#agentResources/resolve',
      service: 'agentResources',
      namespace: 'agentResources',
      method: 'resolve',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#agentResources/resolve:request',
            create: _harness_remote_dsh_wechat_remote_agentResources_resolve_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/resources#ResourceResult',
        create: _harness_remote_dsh_wechat_remote_agentResources_resolve_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/agent-resources.ts","line":107,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatAttachment/prepareBatch',
      service: 'wechatAttachment',
      namespace: 'wechatAttachment',
      method: 'prepareBatch',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/attachment#WechatAttachmentBatchRequest',
            create: _harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/attachment#WechatAttachmentBatchResult',
        create: _harness_remote_dsh_wechat_remote_wechatAttachment_prepareBatch_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/attachment-service.ts","line":133,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatDirectory/create',
      service: 'wechatDirectory',
      namespace: 'wechatDirectory',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryCreateRequest',
            create: _harness_remote_dsh_wechat_remote_wechatDirectory_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryCreateResult',
        create: _harness_remote_dsh_wechat_remote_wechatDirectory_create_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/directory-service.ts","line":254,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatDirectory/list',
      service: 'wechatDirectory',
      namespace: 'wechatDirectory',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryListRequest',
            create: _harness_remote_dsh_wechat_remote_wechatDirectory_list_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryListResult',
        create: _harness_remote_dsh_wechat_remote_wechatDirectory_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/directory-service.ts","line":181,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatDirectory/roots',
      service: 'wechatDirectory',
      namespace: 'wechatDirectory',
      method: 'roots',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryRootsRequest',
            create: _harness_remote_dsh_wechat_remote_wechatDirectory_roots_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryRootsResult',
        create: _harness_remote_dsh_wechat_remote_wechatDirectory_roots_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/directory-service.ts","line":149,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatHistory/detail',
      service: 'wechatHistory',
      namespace: 'wechatHistory',
      method: 'detail',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote#wechatHistory/detail:request',
            create: _harness_remote_dsh_wechat_remote_wechatHistory_detail_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/history#WechatHistoryWindowResult',
        create: _harness_remote_dsh_wechat_remote_wechatHistory_detail_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/history-service.ts","line":196,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatHistory/page',
      service: 'wechatHistory',
      namespace: 'wechatHistory',
      method: 'page',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/history#WechatHistoryWindowRequest',
            create: _harness_remote_dsh_wechat_remote_wechatHistory_page_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/history#WechatHistoryWindowResult',
        create: _harness_remote_dsh_wechat_remote_wechatHistory_page_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/history-service.ts","line":169,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatHistory/window',
      service: 'wechatHistory',
      namespace: 'wechatHistory',
      method: 'window',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/history#WechatHistoryWindowRequest',
            create: _harness_remote_dsh_wechat_remote_wechatHistory_window_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/history#WechatHistoryWindowResult',
        create: _harness_remote_dsh_wechat_remote_wechatHistory_window_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/history-service.ts","line":224,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatHost/describe',
      service: 'wechatHost',
      namespace: 'wechatHost',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/host-info#WechatHostDescribeRequest',
            create: _harness_remote_dsh_wechat_remote_wechatHost_describe_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/host-info#WechatHostDescribeResult',
        create: _harness_remote_dsh_wechat_remote_wechatHost_describe_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/host-info-service.ts","line":88,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "wechatAttachment",
        "exportName": "WechatAttachmentService",
        "members": [
          {
            "kind": "method",
            "name": "prepareBatch",
            "signature": "@Remote('prepareBatch') async prepareBatch( request: WechatAttachmentBatchRequest, signal: AbortSignal, ): Promise<WechatAttachmentBatchResult>"
          }
        ],
        "types": [
          {
            "name": "PreparedWechatAttachment",
            "declaration": "export interface PreparedWechatAttachment {\n    readonly attachmentId: string;\n    readonly descriptor: WechatAttachmentObjectDescriptor;\n}"
          },
          {
            "name": "WechatAttachmentBatchRequest",
            "declaration": "export interface WechatAttachmentBatchRequest {\n    readonly sessionId: string;\n    readonly attachments: readonly WechatAttachmentInput[];\n}"
          },
          {
            "name": "WechatAttachmentBatchResult",
            "declaration": "export type WechatAttachmentBatchResult = { readonly ok: true; readonly value: { readonly descriptors: readonly PreparedWechatAttachment[]; }; } | { readonly ok: false; readonly error: WechatAttachmentError; };"
          },
          {
            "name": "WechatAttachmentError",
            "declaration": "export interface WechatAttachmentError {\n    readonly code: 'invalid-attachment-request' | 'attachment-unavailable' | 'attachment-object-unavailable';\n    readonly message: string;\n}"
          },
          {
            "name": "WechatAttachmentInput",
            "declaration": "export interface WechatAttachmentInput {\n    readonly attachmentId: string;\n    readonly mediaType?: string;\n    readonly name?: string;\n}"
          },
          {
            "name": "WechatAttachmentObjectDescriptor",
            "declaration": "export interface WechatAttachmentObjectDescriptor {\n    readonly v: 1;\n    readonly scheme: 'xsalsa20-poly1305-chunks-v1';\n    readonly objectId: string;\n    readonly key: string;\n    readonly noncePrefix: string;\n    readonly plainBytes: number;\n    readonly cipherBytes: number;\n    readonly chunkBytes: number;\n    readonly contentKind: 'image';\n    readonly mediaType: string;\n    readonly name?: string;\n    readonly expiresAt: number;\n}"
          }
        ]
      },
      {
        "description": "Host-only directory service exposed through the standard DSH Typert gateway.",
        "summary": "Host-only directory service exposed through the standard DSH Typert gateway.",
        "tags": [],
        "jsDoc": "/**\r\n * Host-only directory service exposed through the standard DSH Typert gateway.\r\n */",
        "key": "wechatDirectory",
        "exportName": "WechatDirectoryService",
        "members": [
          {
            "kind": "method",
            "name": "roots",
            "signature": "@Remote('roots') async roots( request: WechatDirectoryRootsRequest, signal: AbortSignal, ): Promise<WechatDirectoryRootsResult>",
            "summary": "Enumerate roots through the selected host adapter; never guess C: through Z:.",
            "jsDoc": "/** Enumerate roots through the selected host adapter; never guess C: through Z:. */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list( request: WechatDirectoryListRequest, signal: AbortSignal, ): Promise<WechatDirectoryListResult>",
            "summary": "List one directory level with the same bounds and path fence as DSH browse.",
            "jsDoc": "/** List one directory level with the same bounds and path fence as DSH browse. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote('create') async create( request: WechatDirectoryCreateRequest, signal: AbortSignal, ): Promise<WechatDirectoryCreateResult>",
            "summary": "Create exactly one child directory; never recurse or accept a path segment.",
            "jsDoc": "/** Create exactly one child directory; never recurse or accept a path segment. */"
          }
        ],
        "types": [
          {
            "name": "DirectoryRootStyle",
            "declaration": "export type DirectoryRootStyle = 'drives' | 'filesystem';"
          },
          {
            "name": "HostPlatformKind",
            "declaration": "export type HostPlatformKind = 'windows' | 'macos' | 'linux' | 'unknown';"
          },
          {
            "name": "PlatformRootKind",
            "declaration": "export type PlatformRootKind = 'local' | 'network' | 'filesystem' | 'home' | 'volume';"
          },
          {
            "name": "WechatDirectoryCreateError",
            "declaration": "export interface WechatDirectoryCreateError {\n    readonly code: 'directory-exists' | 'directory-create-failed';\n    readonly path: string;\n    readonly message: string;\n}"
          },
          {
            "name": "WechatDirectoryCreateRequest",
            "declaration": "export interface WechatDirectoryCreateRequest {\n    readonly path: string;\n    readonly name: string;\n}"
          },
          {
            "name": "WechatDirectoryCreateResult",
            "declaration": "export type WechatDirectoryCreateResult = { readonly ok: true; readonly value: WechatDirectoryCreateValue; } | { readonly ok: false; readonly error: WechatDirectoryCreateError; };"
          },
          {
            "name": "WechatDirectoryCreateValue",
            "declaration": "export interface WechatDirectoryCreateValue {\n    readonly path: string;\n}"
          },
          {
            "name": "WechatDirectoryCrumb",
            "declaration": "export interface WechatDirectoryCrumb {\n    readonly name: string;\n    readonly path: string;\n    readonly hidden: boolean;\n}"
          },
          {
            "name": "WechatDirectoryEntry",
            "declaration": "export interface WechatDirectoryEntry {\n    readonly name: string;\n    readonly path: string;\n    readonly hidden: boolean;\n}"
          },
          {
            "name": "WechatDirectoryListError",
            "declaration": "export interface WechatDirectoryListError {\n    readonly code: 'directory-unreadable' | 'directory-timeout' | 'network-unavailable';\n    readonly path: string;\n    readonly message: string;\n}"
          },
          {
            "name": "WechatDirectoryListRequest",
            "declaration": "export interface WechatDirectoryListRequest {\n    readonly path?: string;\n}"
          },
          {
            "name": "WechatDirectoryListResult",
            "declaration": "export type WechatDirectoryListResult = { readonly ok: true; readonly value: WechatDirectoryListValue; } | { readonly ok: false; readonly error: WechatDirectoryListError; };"
          },
          {
            "name": "WechatDirectoryListValue",
            "declaration": "export interface WechatDirectoryListValue {\n    readonly path: string;\n    readonly home: string;\n    readonly crumbs: readonly WechatDirectoryCrumb[];\n    readonly entries: readonly WechatDirectoryEntry[];\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "WechatDirectoryRoot",
            "declaration": "export interface WechatDirectoryRoot {\n    readonly name: string;\n    readonly path: string;\n    readonly kind: PlatformRootKind;\n    readonly displayRoot?: string;\n}"
          },
          {
            "name": "WechatDirectoryRootsError",
            "declaration": "export interface WechatDirectoryRootsError {\n    readonly code: 'drive-enumeration-failed';\n    readonly message: string;\n}"
          },
          {
            "name": "WechatDirectoryRootsRequest",
            "declaration": "export interface WechatDirectoryRootsRequest {\n}"
          },
          {
            "name": "WechatDirectoryRootsResult",
            "declaration": "export type WechatDirectoryRootsResult = { readonly ok: true; readonly value: WechatDirectoryRootsValue; } | { readonly ok: false; readonly error: WechatDirectoryRootsError; };"
          },
          {
            "name": "WechatDirectoryRootsValue",
            "declaration": "export interface WechatDirectoryRootsValue {\n    readonly home: string;\n    readonly roots: readonly WechatDirectoryRoot[];\n    readonly platform: HostPlatformKind;\n    readonly rootStyle: DirectoryRootStyle;\n}"
          }
        ]
      },
      {
        "tags": [],
        "key": "wechatHistory",
        "exportName": "WechatHistoryService",
        "members": [
          {
            "kind": "method",
            "name": "presentRecord",
            "signature": "presentRecord(sessionId: string, original: HistoryEntry, displayed: HistoryEntry = original, call?: HistoryEntry): HistoryEntry",
            "summary": "Host-only presentation shared by history and realtime peers.",
            "jsDoc": "/** Host-only presentation shared by history and realtime peers.\r\n * Not a Remote: identity is issued here, and detail() rechecks access. */"
          },
          {
            "kind": "method",
            "name": "page",
            "signature": "@Remote('page') async page(request: WechatHistoryWindowRequest, signal: AbortSignal): Promise<WechatHistoryWindowResult>",
            "summary": "New clients explicitly opt into a bounded page contract.",
            "jsDoc": "/** New clients explicitly opt into a bounded page contract. This endpoint\r\n * never uploads history to OSS or recursively completes a partial turn. */"
          },
          {
            "kind": "method",
            "name": "detail",
            "signature": "@Remote('detail') async detail(request: { readonly sessionId: string; readonly reference: string; readonly part?: number; readonly offset?: number }, signal: AbortSignal): Promise<WechatHistoryWindowResult>"
          },
          {
            "kind": "method",
            "name": "window",
            "signature": "@Remote('window') async window( request: WechatHistoryWindowRequest, signal: AbortSignal, ): Promise<WechatHistoryWindowResult>"
          }
        ],
        "types": [
          {
            "name": "HistoryEntry",
            "declaration": "export interface HistoryEntry {\n    readonly event?: { readonly type?: unknown; readonly seq?: unknown; readonly data?: Record<string, unknown>; };\n    readonly [key: string]: unknown;\n}"
          },
          {
            "name": "WechatHistoryRemoteValue",
            "declaration": "export interface WechatHistoryRemoteValue {\n    readonly payloadJson?: string;\n    readonly snapshotJson?: string;\n}"
          },
          {
            "name": "WechatHistoryWindowError",
            "declaration": "export interface WechatHistoryWindowError {\n    readonly code: 'invalid-history-request' | 'history-unavailable' | 'history-pagination-invalid' | 'history-busy' | 'history-detail-unavailable' | 'invocation-unavailable';\n    readonly message: string;\n}"
          },
          {
            "name": "WechatHistoryWindowRequest",
            "declaration": "export interface WechatHistoryWindowRequest {\n    readonly sessionId: string;\n    readonly beforeSeq?: number;\n    readonly maxMessages?: number;\n    readonly delivery?: 'auto' | 'inline';\n    readonly acceptInlineArchive?: boolean;\n}"
          },
          {
            "name": "WechatHistoryWindowResult",
            "declaration": "export type WechatHistoryWindowResult = { readonly ok: true; readonly value: WechatHistoryRemoteValue; } | { readonly ok: false; readonly error: WechatHistoryWindowError; };"
          }
        ]
      },
      {
        "description": "Host-only, authenticated, read-only metadata for the WeChat client.",
        "summary": "Host-only, authenticated, read-only metadata for the WeChat client.",
        "tags": [],
        "jsDoc": "/** Host-only, authenticated, read-only metadata for the WeChat client. */",
        "key": "wechatHost",
        "exportName": "WechatHostInfoService",
        "members": [
          {
            "kind": "method",
            "name": "describe",
            "signature": "@Remote('describe') async describe( request: WechatHostDescribeRequest, signal: AbortSignal, ): Promise<WechatHostDescribeResult>"
          }
        ],
        "types": [
          {
            "name": "AgentCapability",
            "declaration": "export interface AgentCapability {\n    readonly id: string;\n    readonly version: number;\n}"
          },
          {
            "name": "DirectoryRootStyle",
            "declaration": "export type DirectoryRootStyle = 'drives' | 'filesystem';"
          },
          {
            "name": "HostPathStyle",
            "declaration": "export type HostPathStyle = 'windows' | 'posix';"
          },
          {
            "name": "HostPlatformDescriptor",
            "declaration": "export interface HostPlatformDescriptor {\n    readonly kind: HostPlatformKind;\n    readonly name: string;\n    readonly pathStyle: HostPathStyle;\n    readonly directoryRootStyle: DirectoryRootStyle;\n}"
          },
          {
            "name": "HostPlatformKind",
            "declaration": "export type HostPlatformKind = 'windows' | 'macos' | 'linux' | 'unknown';"
          },
          {
            "name": "WechatGateDoorInfo",
            "declaration": "export interface WechatGateDoorInfo {\n    readonly bind: string;\n    readonly port: number;\n    readonly state: 'starting' | 'listening' | 'unavailable' | 'stopped';\n    readonly errorCode: string | null;\n    readonly message: string | null;\n}"
          },
          {
            "name": "WechatGateRuntimeInfo",
            "declaration": "export interface WechatGateRuntimeInfo {\n    readonly profileScope: string;\n    readonly source: 'legacy-default' | 'profile-derived' | 'environment-override';\n    readonly publicDoor: WechatGateDoorInfo;\n    readonly localDoor: WechatGateDoorInfo;\n}"
          },
          {
            "name": "WechatHostDescribeRequest",
            "declaration": "export interface WechatHostDescribeRequest {\n}"
          },
          {
            "name": "WechatHostDescribeResult",
            "declaration": "export type WechatHostDescribeResult = { readonly ok: true; readonly value: WechatHostDescribeValue; };"
          },
          {
            "name": "WechatHostDescribeValue",
            "declaration": "export interface WechatHostDescribeValue {\n    readonly computerName: string;\n    readonly pluginVersion: string;\n    readonly hostArch: string;\n    readonly updateProtocolVersion: 1;\n    readonly descriptorVersion: 1;\n    readonly hostId: string;\n    readonly agentInstanceId: string;\n    readonly agentKind: 'deepseek-harness';\n    readonly agentName: 'DeepSeek Harness';\n    readonly agentVersion: string;\n    readonly hostPlatform: HostPlatformDescriptor;\n    readonly capabilities: readonly AgentCapability[];\n    readonly gate?: WechatGateRuntimeInfo;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}

import { attachLegacySchemaAccess } from './typert-schema-compat.js'
attachLegacySchemaAccess(TYPERT)
