/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WechatAttachmentBatchRequest, WechatAttachmentBatchResult } from '@harness-remote/dsh-wechat-remote/attachment'
import type { WechatDirectoryCreateRequest, WechatDirectoryCreateResult, WechatDirectoryListRequest, WechatDirectoryListResult, WechatDirectoryRootsRequest, WechatDirectoryRootsResult } from '@harness-remote/dsh-wechat-remote/directory'
import type { WechatHistoryWindowRequest, WechatHistoryWindowResult } from '@harness-remote/dsh-wechat-remote/history'
import type { WechatHostDescribeRequest, WechatHostDescribeResult } from '@harness-remote/dsh-wechat-remote/host-info'
import type { ResourceResult } from '@harness-remote/dsh-wechat-remote/resources'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6167656e74496e70757473 {
    capabilities: (request: { scope: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    upload: (request: { scope: string; name: string; data?: string; descriptorJson?: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
  }
  interface TypertRemoteNamespace$6167656e745265736f7572636573 {
    capabilities: (request: { scope: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    chunk: (request: { scope: string; transferId: string; offset: number; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    list: (request: { scope: string; directoryId?: string; cursor?: number; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    prepare: (request: { scope: string; id: string; delivery: 'chunks' | 'object'; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    release: (request: { scope: string; transferId: string; }) => Promise<RemoteResult<ResourceResult>>
    resolve: (request: { scope: string; reference: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
  }
  interface TypertRemoteNamespace$7765636861744174746163686d656e74 {
    prepareBatch: (request: WechatAttachmentBatchRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatAttachmentBatchResult>>
  }
  interface TypertRemoteNamespace$7765636861744469726563746f7279 {
    create: (request: WechatDirectoryCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatDirectoryCreateResult>>
    list: (request: WechatDirectoryListRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatDirectoryListResult>>
    roots: (request: WechatDirectoryRootsRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatDirectoryRootsResult>>
  }
  interface TypertRemoteNamespace$776563686174486973746f7279 {
    window: (request: WechatHistoryWindowRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatHistoryWindowResult>>
  }
  interface TypertRemoteNamespace$776563686174486f7374 {
    describe: (request: WechatHostDescribeRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatHostDescribeResult>>
  }
  interface TypertRemoteMap {
    'agentInputs/capabilities': (request: { scope: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    'agentInputs/upload': (request: { scope: string; name: string; data?: string; descriptorJson?: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    'agentResources/capabilities': (request: { scope: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    'agentResources/chunk': (request: { scope: string; transferId: string; offset: number; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    'agentResources/list': (request: { scope: string; directoryId?: string; cursor?: number; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    'agentResources/prepare': (request: { scope: string; id: string; delivery: 'chunks' | 'object'; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    'agentResources/release': (request: { scope: string; transferId: string; }) => Promise<RemoteResult<ResourceResult>>
    'agentResources/resolve': (request: { scope: string; reference: string; }, signal?: AbortSignal) => Promise<RemoteResult<ResourceResult>>
    'wechatAttachment/prepareBatch': (request: WechatAttachmentBatchRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatAttachmentBatchResult>>
    'wechatDirectory/create': (request: WechatDirectoryCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatDirectoryCreateResult>>
    'wechatDirectory/list': (request: WechatDirectoryListRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatDirectoryListResult>>
    'wechatDirectory/roots': (request: WechatDirectoryRootsRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatDirectoryRootsResult>>
    'wechatHistory/window': (request: WechatHistoryWindowRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatHistoryWindowResult>>
    'wechatHost/describe': (request: WechatHostDescribeRequest, signal?: AbortSignal) => Promise<RemoteResult<WechatHostDescribeResult>>
  }
  interface TypertRemoteNamespaceMap {
    'agentInputs': TypertRemoteNamespace$6167656e74496e70757473
    'agentResources': TypertRemoteNamespace$6167656e745265736f7572636573
    'wechatAttachment': TypertRemoteNamespace$7765636861744174746163686d656e74
    'wechatDirectory': TypertRemoteNamespace$7765636861744469726563746f7279
    'wechatHistory': TypertRemoteNamespace$776563686174486973746f7279
    'wechatHost': TypertRemoteNamespace$776563686174486f7374
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
