/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _harness_remote_dsh_wechat_remote_wechatDirectory_create_parameter_0$schema = z.object({
  'path': z.string().readonly(),
  'name': z.string().readonly(),
})
const _harness_remote_dsh_wechat_remote_wechatDirectory_create_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'path': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("directory-exists"), z.literal("directory-create-failed")]).readonly(),
  'path': z.string().readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _harness_remote_dsh_wechat_remote_wechatDirectory_list_parameter_0$schema = z.object({
  'path': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const _harness_remote_dsh_wechat_remote_wechatDirectory_list_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'path': z.string().readonly(),
  'home': z.string().readonly(),
  'crumbs': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'truncated': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("directory-unreadable"), z.literal("directory-timeout"), z.literal("network-unavailable")]).readonly(),
  'path': z.string().readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _harness_remote_dsh_wechat_remote_wechatDirectory_roots_parameter_0$schema = z.object({})
const _harness_remote_dsh_wechat_remote_wechatDirectory_roots_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'home': z.string().readonly(),
  'roots': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'kind': z.union([z.literal("local"), z.literal("network"), z.literal("filesystem")]).readonly(),
  'displayRoot': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.literal("drive-enumeration-failed").readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _harness_remote_dsh_wechat_remote_wechatHistory_window_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'beforeSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'maxMessages': z.union([z.undefined(), z.number()]).readonly().optional(),
})
const _harness_remote_dsh_wechat_remote_wechatHistory_window_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'payloadJson': z.string().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("invalid-history-request"), z.literal("history-unavailable"), z.literal("history-pagination-invalid")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _harness_remote_dsh_wechat_remote_wechatHost_describe_parameter_0$schema = z.object({})
const _harness_remote_dsh_wechat_remote_wechatHost_describe_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'computerName': z.string().readonly(),
  'pluginVersion': z.string().readonly(),
  'descriptorVersion': z.literal(1).readonly(),
  'hostId': z.string().readonly(),
  'agentInstanceId': z.string().readonly(),
  'agentKind': z.literal("deepseek-harness").readonly(),
  'agentName': z.literal("DeepSeek Harness").readonly(),
  'agentVersion': z.string().readonly(),
  'capabilities': z.array(z.object({
  'id': z.string().readonly(),
  'version': z.number().readonly(),
})).readonly(),
  'gate': z.union([z.undefined(), z.object({
  'profileScope': z.string().readonly(),
  'source': z.union([z.literal("legacy-default"), z.literal("profile-derived"), z.literal("environment-override")]).readonly(),
  'publicDoor': z.object({
  'bind': z.string().readonly(),
  'port': z.number().readonly(),
  'state': z.union([z.literal("starting"), z.literal("listening"), z.literal("unavailable"), z.literal("stopped")]).readonly(),
  'errorCode': z.union([z.literal(null), z.string()]).readonly(),
  'message': z.union([z.literal(null), z.string()]).readonly(),
}).readonly(),
  'localDoor': z.object({
  'bind': z.string().readonly(),
  'port': z.number().readonly(),
  'state': z.union([z.literal("starting"), z.literal("listening"), z.literal("unavailable"), z.literal("stopped")]).readonly(),
  'errorCode': z.union([z.literal(null), z.string()]).readonly(),
  'message': z.union([z.literal(null), z.string()]).readonly(),
}).readonly(),
})]).readonly().optional(),
}).readonly(),
})

export const TYPERT = {
  package: '@harness-remote/dsh-wechat-remote',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@harness-remote/dsh-wechat-remote#wechatDirectory/create',
      service: 'wechatDirectory',
      namespace: 'wechatDirectory',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryCreateRequest',
            schema: _harness_remote_dsh_wechat_remote_wechatDirectory_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryCreateResult',
        schema: _harness_remote_dsh_wechat_remote_wechatDirectory_create_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/directory-service.ts","line":253,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatDirectory/list',
      service: 'wechatDirectory',
      namespace: 'wechatDirectory',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryListRequest',
            schema: _harness_remote_dsh_wechat_remote_wechatDirectory_list_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryListResult',
        schema: _harness_remote_dsh_wechat_remote_wechatDirectory_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/directory-service.ts","line":180,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatDirectory/roots',
      service: 'wechatDirectory',
      namespace: 'wechatDirectory',
      method: 'roots',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryRootsRequest',
            schema: _harness_remote_dsh_wechat_remote_wechatDirectory_roots_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/directory#WechatDirectoryRootsResult',
        schema: _harness_remote_dsh_wechat_remote_wechatDirectory_roots_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/directory-service.ts","line":147,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatHistory/window',
      service: 'wechatHistory',
      namespace: 'wechatHistory',
      method: 'window',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/history#WechatHistoryWindowRequest',
            schema: _harness_remote_dsh_wechat_remote_wechatHistory_window_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/history#WechatHistoryWindowResult',
        schema: _harness_remote_dsh_wechat_remote_wechatHistory_window_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/history-service.ts","line":112,"column":9},
    },
    {
      id: '@harness-remote/dsh-wechat-remote#wechatHost/describe',
      service: 'wechatHost',
      namespace: 'wechatHost',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@harness-remote/dsh-wechat-remote/host-info#WechatHostDescribeRequest',
            schema: _harness_remote_dsh_wechat_remote_wechatHost_describe_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@harness-remote/dsh-wechat-remote/host-info#WechatHostDescribeResult',
        schema: _harness_remote_dsh_wechat_remote_wechatHost_describe_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-wechat-remote/src/host-info-service.ts","line":84,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host-only directory service exposed through the standard DSH Typert gateway.",
        "summary": "Host-only directory service exposed through the standard DSH Typert gateway.",
        "tags": [],
        "jsDoc": "/**\r\n * Host-only directory service exposed through the standard DSH Typert gateway.\r\n */",
        "key": "wechatDirectory",
        "exportName": "WechatDirectoryService",
        "members": [
          {
            "kind": "method",
            "name": "roots",
            "signature": "@Remote('roots') async roots( request: WechatDirectoryRootsRequest, signal: AbortSignal, ): Promise<WechatDirectoryRootsResult>",
            "summary": "Enumerate real filesystem roots once; never guess C: through Z:.",
            "jsDoc": "/** Enumerate real filesystem roots once; never guess C: through Z:. */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list( request: WechatDirectoryListRequest, signal: AbortSignal, ): Promise<WechatDirectoryListResult>",
            "summary": "List one directory level with the same bounds and path fence as DSH browse.",
            "jsDoc": "/** List one directory level with the same bounds and path fence as DSH browse. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote('create') async create( request: WechatDirectoryCreateRequest, signal: AbortSignal, ): Promise<WechatDirectoryCreateResult>",
            "summary": "Create exactly one child directory; never recurse or accept a path segment.",
            "jsDoc": "/** Create exactly one child directory; never recurse or accept a path segment. */"
          }
        ],
        "types": [
          {
            "name": "WechatDirectoryCreateError",
            "declaration": "export interface WechatDirectoryCreateError {\n    readonly code: 'directory-exists' | 'directory-create-failed';\n    readonly path: string;\n    readonly message: string;\n}"
          },
          {
            "name": "WechatDirectoryCreateRequest",
            "declaration": "export interface WechatDirectoryCreateRequest {\n    readonly path: string;\n    readonly name: string;\n}"
          },
          {
            "name": "WechatDirectoryCreateResult",
            "declaration": "export type WechatDirectoryCreateResult = { readonly ok: true; readonly value: WechatDirectoryCreateValue; } | { readonly ok: false; readonly error: WechatDirectoryCreateError; };"
          },
          {
            "name": "WechatDirectoryCreateValue",
            "declaration": "export interface WechatDirectoryCreateValue {\n    readonly path: string;\n}"
          },
          {
            "name": "WechatDirectoryCrumb",
            "declaration": "export interface WechatDirectoryCrumb {\n    readonly name: string;\n    readonly path: string;\n    readonly hidden: boolean;\n}"
          },
          {
            "name": "WechatDirectoryEntry",
            "declaration": "export interface WechatDirectoryEntry {\n    readonly name: string;\n    readonly path: string;\n    readonly hidden: boolean;\n}"
          },
          {
            "name": "WechatDirectoryListError",
            "declaration": "export interface WechatDirectoryListError {\n    readonly code: 'directory-unreadable' | 'directory-timeout' | 'network-unavailable';\n    readonly path: string;\n    readonly message: string;\n}"
          },
          {
            "name": "WechatDirectoryListRequest",
            "declaration": "export interface WechatDirectoryListRequest {\n    readonly path?: string;\n}"
          },
          {
            "name": "WechatDirectoryListResult",
            "declaration": "export type WechatDirectoryListResult = { readonly ok: true; readonly value: WechatDirectoryListValue; } | { readonly ok: false; readonly error: WechatDirectoryListError; };"
          },
          {
            "name": "WechatDirectoryListValue",
            "declaration": "export interface WechatDirectoryListValue {\n    readonly path: string;\n    readonly home: string;\n    readonly crumbs: readonly WechatDirectoryCrumb[];\n    readonly entries: readonly WechatDirectoryEntry[];\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "WechatDirectoryRoot",
            "declaration": "export interface WechatDirectoryRoot {\n    readonly name: string;\n    readonly path: string;\n    readonly kind: 'local' | 'network' | 'filesystem';\n    readonly displayRoot?: string;\n}"
          },
          {
            "name": "WechatDirectoryRootsError",
            "declaration": "export interface WechatDirectoryRootsError {\n    readonly code: 'drive-enumeration-failed';\n    readonly message: string;\n}"
          },
          {
            "name": "WechatDirectoryRootsRequest",
            "declaration": "export interface WechatDirectoryRootsRequest {\n}"
          },
          {
            "name": "WechatDirectoryRootsResult",
            "declaration": "export type WechatDirectoryRootsResult = { readonly ok: true; readonly value: WechatDirectoryRootsValue; } | { readonly ok: false; readonly error: WechatDirectoryRootsError; };"
          },
          {
            "name": "WechatDirectoryRootsValue",
            "declaration": "export interface WechatDirectoryRootsValue {\n    readonly home: string;\n    readonly roots: readonly WechatDirectoryRoot[];\n}"
          }
        ]
      },
      {
        "tags": [],
        "key": "wechatHistory",
        "exportName": "WechatHistoryService",
        "members": [
          {
            "kind": "method",
            "name": "window",
            "signature": "@Remote('window') async window( request: WechatHistoryWindowRequest, signal: AbortSignal, ): Promise<WechatHistoryWindowResult>"
          }
        ],
        "types": [
          {
            "name": "WechatHistoryRemoteValue",
            "declaration": "export interface WechatHistoryRemoteValue {\n    readonly payloadJson: string;\n}"
          },
          {
            "name": "WechatHistoryWindowError",
            "declaration": "export interface WechatHistoryWindowError {\n    readonly code: 'invalid-history-request' | 'history-unavailable' | 'history-pagination-invalid';\n    readonly message: string;\n}"
          },
          {
            "name": "WechatHistoryWindowRequest",
            "declaration": "export interface WechatHistoryWindowRequest {\n    readonly sessionId: string;\n    readonly beforeSeq?: number;\n    readonly maxMessages?: number;\n}"
          },
          {
            "name": "WechatHistoryWindowResult",
            "declaration": "export type WechatHistoryWindowResult = { readonly ok: true; readonly value: WechatHistoryRemoteValue; } | { readonly ok: false; readonly error: WechatHistoryWindowError; };"
          }
        ]
      },
      {
        "description": "Host-only, authenticated, read-only metadata for the WeChat client.",
        "summary": "Host-only, authenticated, read-only metadata for the WeChat client.",
        "tags": [],
        "jsDoc": "/** Host-only, authenticated, read-only metadata for the WeChat client. */",
        "key": "wechatHost",
        "exportName": "WechatHostInfoService",
        "members": [
          {
            "kind": "method",
            "name": "describe",
            "signature": "@Remote('describe') async describe( request: WechatHostDescribeRequest, signal: AbortSignal, ): Promise<WechatHostDescribeResult>"
          }
        ],
        "types": [
          {
            "name": "AgentCapability",
            "declaration": "export interface AgentCapability {\n    readonly id: string;\n    readonly version: number;\n}"
          },
          {
            "name": "WechatGateDoorInfo",
            "declaration": "export interface WechatGateDoorInfo {\n    readonly bind: string;\n    readonly port: number;\n    readonly state: 'starting' | 'listening' | 'unavailable' | 'stopped';\n    readonly errorCode: string | null;\n    readonly message: string | null;\n}"
          },
          {
            "name": "WechatGateRuntimeInfo",
            "declaration": "export interface WechatGateRuntimeInfo {\n    readonly profileScope: string;\n    readonly source: 'legacy-default' | 'profile-derived' | 'environment-override';\n    readonly publicDoor: WechatGateDoorInfo;\n    readonly localDoor: WechatGateDoorInfo;\n}"
          },
          {
            "name": "WechatHostDescribeRequest",
            "declaration": "export interface WechatHostDescribeRequest {\n}"
          },
          {
            "name": "WechatHostDescribeResult",
            "declaration": "export type WechatHostDescribeResult = { readonly ok: true; readonly value: WechatHostDescribeValue; };"
          },
          {
            "name": "WechatHostDescribeValue",
            "declaration": "export interface WechatHostDescribeValue {\n    readonly computerName: string;\n    readonly pluginVersion: string;\n    readonly descriptorVersion: 1;\n    readonly hostId: string;\n    readonly agentInstanceId: string;\n    readonly agentKind: 'deepseek-harness';\n    readonly agentName: 'DeepSeek Harness';\n    readonly agentVersion: string;\n    readonly capabilities: readonly AgentCapability[];\n    readonly gate?: WechatGateRuntimeInfo;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
